name: publish package

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.*]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn

    - name: Publish package to npmjs.com
      env: 
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        yarn config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        yarn publish
